[project]
name = "yuxi-know"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "colorlog>=6.9.0",
    "dashscope>=1.23.2",
    "docx2txt>=0.9",
    "fastapi>=0.115.12",
    "flagembedding>=1.3.4",
    "langchain-community>=0.3.22",
    "langchain-deepseek>=0.1.3",
    "langchain-huggingface>=0.2.0",
    "langchain-openai>=0.3.14",
    "langchain-together>=0.3.0",
    "langgraph>=0.3.34",
    "langgraph-checkpoint-sqlite>=2.0.7",
    "langsmith>=0.3.37",
    "llama-index>=0.12.33",
    "llama-index-readers-file>=0.4.7",
    "neo4j>=5.28.1",
    "openai>=1.76.0",
    "opencv-python-headless>=4.11.0.86",
    "paddleocr>=2.10.0",
    "pyjwt>=2.8.0",
    "pymilvus>=2.5.8",
    "pymupdf>=1.25.5",
    "python-dotenv>=1.1.0",
    "python-jose[cryptography]>=3.4.0",
    "python-multipart>=0.0.20",
    "pyyaml>=6.0.2",
    "qianfan>=0.4.12.3",
    "rapidocr-onnxruntime>=1.4.4",
    "sentencepiece>=0.2.0",
    "tavily-python>=0.7.0",
    "unstructured>=0.17.2",
    "uvicorn[standard]>=0.34.2",
    "zhipuai>=2.1.5.20250421",
]
